# Generated by Django 3.2.16 on 2022-11-28 13:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
