# Generated by Django 3.2.16 on 2022-11-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20221128_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slogan',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
