# Generated by Django 3.2.16 on 2022-12-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default=1, upload_to='profile_pics/%Y%m%d'),
            preserve_default=False,
        ),
    ]
