# Generated by Django 3.2.16 on 2022-12-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default='profile_pic.jpg', upload_to='profile_pics/%Y%m%d'),
        ),
    ]
