# Generated by Django 3.2.16 on 2022-12-05 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_profile_pic'),
        ('blog', '0005_remove_comment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='store.customer'),
        ),
    ]
